backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: pages
    label: Pages
    files:
      - label: About Us
        name: about
        file: content/about.json
        fields:
          - { label: "Body (EN)", name: body_en, widget: markdown }
          - { label: "Body (KA)", name: body_ka, widget: markdown }
      - label: EGAIS License
        name: egais
        file: content/egais.json
        fields:
          - { label: "Body (EN)", name: body_en, widget: markdown }
          - { label: "Body (KA)", name: body_ka, widget: markdown }

  - name: labels
    label: Consumables — Labels
    file: content/consumables_labels.json
    fields:
      - label: Sizes
        name: sizes
        widget: list
        fields:
          - { label: Dimension, name: dimension }
          - { label: "Note (EN)", name: note_en, required: false }
          - { label: "Note (KA)", name: note_ka, required: false }
          - { label: Features, name: features, widget: list, required: false }

  - name: ribbons
    label: Consumables — Wax Ribbons
    file: content/consumables_ribbons.json
    fields:
      - label: Sizes
        name: sizes
        widget: list
        fields:
          - { label: Dimension, name: dimension }
          - { label: "Note (EN)", name: note_en, required: false }
          - { label: "Note (KA)", name: note_ka, required: false }
          - { label: Features, name: features, widget: list, required: false }

  - name: marking
    label: Marking Equipment
    file: content/marking.json
    fields:
      - label: Items
        name: items
        widget: list
        fields:
          - { label: "Title (EN)", name: title_en }
          - { label: "Title (KA)", name: title_ka }
          - { label: "Description (EN)", name: description_en, widget: text, required: false }
          - { label: "Description (KA)", name: description_ka, widget: text, required: false }
          - { label: Images, name: images, widget: list, field: { label: Image, name: image, widget: image } }
          - { label: Link, name: link, required: false }
